---
title: Demo De SiteLeaf
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
title-bold: Demo
title-normal: por Aguara
email: info@aguara.io
description: Un blog responsive hecho en Jekyll y Siteleaf
baseurl: 
url: https://doctorfrancia.github.io/demoelefante.github.io/
author: 
street_address: Roque Centurion Miranda
city: Asunción
state: TN
zip_code: 55555
country: Paraguay
phone: "(0981)419-228"
gems:
- jekyll-sitemap
- jekyll-seo-tag
- jekyll-feed
- jemoji
tiles-source: posts
tiles-count: 6
500px_url: 
facebook_url: 
github_url: 
gitlab_url: https://gitlab.com/u/andrewbanchich
googleplus_url: https://plus.google.com/u/0/+AndrewBanchich
instagram_url: https://instagram.com
linkedin_url: 
pinterest_url: 
slack_url: 
twitter_url: https://twitter.com/martincubilla
markdown: kramdown
twitter:
  username: martincubilla
facebook:
  app_id: 
  publisher: 
  admins: 
logo: "/uploads/2.jpg"
google_site_verification: 
